PierresTreats/Models/Treat.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PierresTreats.Models;


public class Treat
{
  public int TreatId { get; set; }
  [Required(ErrorMessage = "Please enter a name for the treat.")]
  public string TreatName { get; set; }
  public List<FlavorTreat> JoinEntities { get; set; }
}

PierresTreats/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc;
using PierresTreats.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;


namespace PierresTreats.Controllers;

[Authorize]
public class TreatsController : Controller
{
  private readonly PierresTreatsContext _db;

  public TreatsController(PierresTreatsContext db)
  {
    _db = db;
  }
  
  [AllowAnonymous]
  public ActionResult Index()
  {
    return View(_db.Treats.ToList());
  }

  public ActionResult Create()
  {
    return View();
  }

  [HttpPost]
  public ActionResult Create(Treat treat)
  {
    if (!ModelState.IsValid)
    {
      return View(treat);
    }
    else
    {
      _db.Treats.Add(treat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }

  [AllowAnonymous]
  public ActionResult Details(int id)
  {
    ViewBag.Flavors = _db.Flavors.ToList();
    Treat thisTreat = _db.Treats
      .Include(treat => treat.JoinEntities)
      .ThenInclude(join => join.Flavor)
      .FirstOrDefault(treat => treat.TreatId == id);
    return View(thisTreat);
  }

  public ActionResult AddFlavor(int id)
  {
    Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
    ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName");
    return View(thisTreat);
  }

  [HttpPost]
  public ActionResult AddFlavor(Treat treat, int flavorId)
  {
    #nullable enable
    FlavorTreat? joinEntity =_db.FlavorTreats.FirstOrDefault(join => (join.FlavorId == flavorId && join.TreatId == treat.TreatId));
    #nullable disable
    if (joinEntity == null && flavorId != 0)
    {
      _db.FlavorTreats.Add(new FlavorTreat() { FlavorId = flavorId, TreatId = treat.TreatId });
      _db.SaveChanges();
    }
    return RedirectToAction("Details", new { id = treat.TreatId});
  }

  public ActionResult Edit(int id)
  {
    Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
    return View(thisTreat);
  }

  [HttpPost]
  public ActionResult Edit(Treat treat)
  {
    if (!ModelState.IsValid)
    {
      return View(treat);
    }
    else
    {
      _db.Treats.Update(treat);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = treat.TreatId });
    }
  }

  public ActionResult Delete(int id)
  {
    Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
    return View(thisTreat);
  }

  [HttpPost, ActionName("Delete")]
  public ActionResult DeleteConfirmed(int id)
  {
    Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
    _db.Treats.Remove(thisTreat);
    _db.SaveChanges();
    return RedirectToAction("Index");
  }

  [HttpPost]
  public ActionResult DeleteFlavor(int joinId)
  {
    FlavorTreat joinEntry = _db.FlavorTreats.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
    _db.FlavorTreats.Remove(joinEntry);
    _db.SaveChanges();
    return RedirectToAction("Details", new { id = joinEntry.TreatId });
  }
}

PierresTreats/Views/Treats/AddFlavor.cshtml
@{
  Layout = "_Layout";
}

@model PierresTreats.Models.Treat

<h4>Attach @Html.DisplayFor(model => model.TreatName) a flavor</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.TreatId)

  @Html.Label("Select Flavor")
  @Html.DropDownList("FlavorId")

  <input type="submit" value="Save" />
}

<a href='@Url.Action("Index")'>
    <button type="button">Back to List</button>
</a>

PierresTreats/Views/Treats/Create.cshtml
@{
  Layout = "_Layout";
}

@model PierresTreats.Models.Treat


<h2>Add a new Treat</h2>
<hr />

@using (Html.BeginForm())
{
  @Html.Label("Treat Name ")
  <br>
  @Html.TextBoxFor(model => model.TreatName)
  <p>@Html.ValidationMessageFor(model => model.TreatName, "", new { @class = "text-danger" })</p> 

  <input type="submit" value="Add new treat"/>
}

PierresTreats/Views/Treats/Delete.cshtml
@{
  Layout = "_Layout";
}

@model PierresTreats.Models.Treat

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayName("Treat Name"): @Html.DisplayFor(model => model.TreatName)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

@Html.ActionLink("Back to List", "Index")

PierresTreats/Views/Treats/Details.cshtml
@{
  Layout = "_Layout";
}

@using PierresTreats.Models
@model PierresTreats.Models.Treat

<h2>Treat Details</h2>
<hr />
<h3>@Html.DisplayName("Treat Name"): @Html.DisplayFor(model => model.TreatName)</h3>

@if (Model.JoinEntities.Count == 0)
{
  <p>This treat does not have any associated flavor attached to it.</p>
}
else
{
  <h4>Current flavors attached:</h4>
  <ul>
    @foreach (FlavorTreat join in Model.JoinEntities)
    {
      @using (Html.BeginForm("DeleteFlavor", "Treats"))
      {
        <li>
          @join.Flavor.FlavorName
          @Html.Hidden("joinId", join.FlavorTreatId)
          <input class="delete" type="submit" value="Delete" />
        </li>
      }
    }
  </ul>
}

@if (@ViewBag.Flavors.Count == 0)
{
  <a href="">
    <button type="button" disabled="">No flavors to assign</button>
  </a>
}
else
{
  <a href='@Url.Action("AddFlavor", new { id = Model.TreatId })'>
    <button type="button">Attach a Flavor</button>
  </a>
}

<a href='@Url.Action("Delete", new { id = Model.TreatId })'>
    <button type="button">Delete Treat</button>
</a>
<a href='@Url.Action("Edit", new { id = Model.TreatId })'>
    <button type="button">Edit Treat</button>
</a>

PierresTreats/Views/Treats/Edit.cshtml
@{
  Layout = "_Layout";
}

@model PierresTreats.Models.Treat

<h2>Editing @Html.DisplayFor(model => model.TreatName)</h2>
<hr />

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.TreatId)

  @Html.Label("Updated Treat Name") 
  <br>
  @Html.EditorFor(model => model.TreatName)
  <p>@Html.ValidationMessageFor(model => model.TreatName, "", new { @class = "text-danger" })</p> 

  <input type="submit" value="Save" />
}

<a href='@Url.Action("Index")'>
    <button type="button">Back to List</button>
</a>

PierresTreats/Views/Treats/Index.cshtml
@{
  Layout = "_Layout";
}

@using PierresTreats.Models

<h3>Available Treats</h3>

@if (Model.Count == 0)
{
  <p>There are no treats in the database.</p>
}
else
{
  <ul>
    @foreach (Treat treat in Model)
    {
      <li>@Html.ActionLink($"{treat.TreatName}", "Details", new { id = treat.TreatId })</li>
    }
  </ul>
}

<a href='@Url.Action("Create")'>
    <button type="button">Add a new treat</button>
</a>