PierresTreats/Models/Flavor.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PierresTreats.Models;


public class Flavor
{
  public int FlavorId { get; set; }
  [Required(ErrorMessage = "Please enter a name for the flavor.")]
  public string FlavorName { get; set; }
  public List<FlavorTreat> JoinEntities { get; set; }
}

PierresTreats/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc;
using PierresTreats.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;


namespace PierresTreats.Controllers;

[Authorize]
public class FlavorsController : Controller
{
  private readonly PierresTreatsContext _db;

  public FlavorsController(PierresTreatsContext db)
  {
    _db = db;
  }
  
  [AllowAnonymous]
  public ActionResult Index()
  {
    return View(_db.Flavors.ToList());
  }

  public ActionResult Create()
  {
    return View();
  }

  [HttpPost]
  public ActionResult Create(Flavor flavor)
  {
    if (!ModelState.IsValid)
    {
      return View(flavor);
    }
    else
    {
      _db.Flavors.Add(flavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }

  [AllowAnonymous]
  public ActionResult Details(int id)
  {
    ViewBag.Treats = _db.Treats.ToList();
    Flavor thisFlavor = _db.Flavors
      .Include(flavor => flavor.JoinEntities)
      .ThenInclude(join => join.Treat)
      .FirstOrDefault(flavor => flavor.FlavorId == id);
    return View(thisFlavor);
  }

  public ActionResult AddTreat(int id)
  {
    Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
    ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "TreatName");
    return View(thisFlavor);
  }

  [HttpPost]
  public ActionResult AddTreat(Flavor flavor, int treatId)
  {
    #nullable enable
    FlavorTreat? joinEntity =_db.FlavorTreats.FirstOrDefault(join => (join.TreatId == treatId && join.FlavorId == flavor.FlavorId));
    #nullable disable
    if (joinEntity == null && treatId != 0)
    {
      _db.FlavorTreats.Add(new FlavorTreat() { TreatId = treatId, FlavorId = flavor.FlavorId });
      _db.SaveChanges();
    }
    return RedirectToAction("Details", new { id = flavor.FlavorId});
  }

  public ActionResult Edit(int id)
  {
    Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
    return View(thisFlavor);
  }

  [HttpPost]
  public ActionResult Edit(Flavor flavor)
  {
    if (!ModelState.IsValid)
    {
      return View(flavor);
    }
    else
    {
      _db.Flavors.Update(flavor);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = flavor.FlavorId });
    }
  }

  public ActionResult Delete(int id)
  {
    Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
    return View(thisFlavor);
  }

  [HttpPost, ActionName("Delete")]
  public ActionResult DeleteConfirmed(int id)
  {
    Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
    _db.Flavors.Remove(thisFlavor);
    _db.SaveChanges();
    return RedirectToAction("Index");
  }

  [HttpPost]
  public ActionResult DeleteTreat(int joinId)
  {
    FlavorTreat joinEntry = _db.FlavorTreats.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
    _db.FlavorTreats.Remove(joinEntry);
    _db.SaveChanges();
    return RedirectToAction("Details", new { id = joinEntry.FlavorId });
  }
}

PierresTreats/Views/Flavors/AddTreat.cshtml
@{
  Layout = "_Layout";
}

@model PierresTreats.Models.Flavor

<h4>Attach @Html.DisplayFor(model => model.FlavorName) to a treat</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.FlavorId)

  @Html.Label("Select Treat")
  @Html.DropDownList("TreatId")

  <input type="submit" value="Save" />
}

<a href='@Url.Action("Index")'>
    <button type="button">Back to List</button>
</a>

PierresTreats/Views/Flavors/Create.cshtml
@{
  Layout = "_Layout";
}

@model PierresTreats.Models.Flavor


<h2>Add a new Flavor</h2>
<hr />

@using (Html.BeginForm())
{
  @Html.Label("Flavor Name ")
  <br>
  @Html.TextBoxFor(model => model.FlavorName)
  <p>@Html.ValidationMessageFor(model => model.FlavorName, "", new { @class = "text-danger" })</p> 

  <input type="submit" value="Add new flavor"/>
}

PierresTreats/Views/Flavors/Delete.cshtml
@{
  Layout = "_Layout";
}

@model PierresTreats.Models.Flavor

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayName("Flavor Name"): @Html.DisplayFor(model => model.FlavorName)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

@Html.ActionLink("Back to List", "Index")

PierresTreats/Views/Flavors/Details.cshtml
@{
  Layout = "_Layout";
}

@using PierresTreats.Models
@model PierresTreats.Models.Flavor

<h2>Flavor Details</h2>
<hr />
<h3>@Html.DisplayName("Flavor Name"): @Html.DisplayFor(model => model.FlavorName)</h3>

@if (Model.JoinEntities.Count == 0)
{
  <p>This flavor does not have any associated treats attached to it.</p>
}
else
{
  <h4>Current treats attached:</h4>
  <ul>
    @foreach (FlavorTreat join in Model.JoinEntities)
    {
      @using (Html.BeginForm("DeleteTreat", "Flavors"))
      {
        <li>
          @join.Treat.TreatName
          @Html.Hidden("joinId", join.FlavorTreatId)
          <input class="delete" type="submit" value="Delete" />
        </li>
      }
    }
  </ul>
}

@if (@ViewBag.Treats.Count == 0)
{
  <a href="">
    <button type="button" disabled="">No treats to assign</button>
  </a>
}
else
{
  <a href='@Url.Action("AddTreat", new { id = Model.FlavorId })'>
    <button type="button">Attach a Treat</button>
  </a>
}

<a href='@Url.Action("Delete", new { id = Model.FlavorId })'>
    <button type="button">Delete Flavor</button>
</a>
<a href='@Url.Action("Edit", new { id = Model.FlavorId })'>
    <button type="button">Edit Flavor</button>
</a>

PierresTreats/Views/Flavors/Edit.cshtml
@{
  Layout = "_Layout";
}

@model PierresTreats.Models.Flavor

<h2>Editing @Html.DisplayFor(model => model.FlavorName)</h2>
<hr />

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.FlavorId)

  @Html.Label("Updated Flavor Name") 
  <br>
  @Html.EditorFor(model => model.FlavorName)
  <p>@Html.ValidationMessageFor(model => model.FlavorName, "", new { @class = "text-danger" })</p> 

  <input type="submit" value="Save" />
}

<a href='@Url.Action("Index")'>
    <button type="button">Back to List</button>
</a>

PierresTreats/Views/Flavors/Index.cshtml
@{
  Layout = "_Layout";
}

@using PierresTreats.Models

<h3>Available Flavors</h3>

@if (Model.Count == 0)
{
  <p>There are no flavors in the database.</p>
}
else
{
  <ul>
    @foreach (Flavor flavor in Model)
    {
      <li>@Html.ActionLink($"{flavor.FlavorName}", "Details", new { id = flavor.FlavorId })</li>
    }
  </ul>
}

<a href='@Url.Action("Create")'>
    <button type="button">Add a new flavor</button>
</a>